#!/bin/sh

# Perform a single simulation and plot the results as heap growth
# ratios and utilization ratios in Gnuplot

set -e

if [ "$1" = -h -o "$1" = --help ]; then
    python3 simulate.py "$@"
    exit
fi

python3 simulate.py "$@" > /tmp/gcpacing.dat
gnuplot --persist -e "\
set multiplot layout 2, 1;
set lmargin at screen 0.15;
set offsets 0, 0, graph 0.1, graph 0.1;
set style data lines;
set xlabel '';
set xtics format '';
set ylabel 'Heap ratio';
plot '/tmp/gcpacing.dat' using (column('H_a')/column('H_m(n-1)')-1) title 'h_a' lw 2, \
     '' using (column('H_g')/column('H_m(n-1)')-1) title 'h_g' lw 2, \
     '' using (column('H_t')/column('H_m(n-1)')-1) title 'h_t' lw 2;
set xlabel 'GC cycle';
set xtics format '% g';
set ylabel 'CPU';
plot [*:*] [0:1] for [n=9:10] '' using 1:n with lines lw 2 title col;
unset multiplot"
