#!/bin/sh

# Perform a single simulation and plot the results as absolute heap
# sizes and utilization ratios in Gnuplot

set -e

if [ "$1" = -h -o "$1" = --help ]; then
    ./simulate "$@"
    exit
fi

./simulate "$@" > /tmp/gcpacing.dat
gnuplot --persist -e "filename='/tmp/gcpacing.dat'" plot-abs.gnuplot
