#!/bin/sh

# Simulate a range of w_true, pointerScanNS, and allocPeriodNS. The
# result can be plotted with all.gnuplot.

set -e

parallel --keep-order --header : --eta --halt 2 \
    ./simulate --w_true {w_true} --pointerScanNS {pointerScanNS} --allocPeriodNS {allocPeriodNS} \
    ::: w_true 0.0125 \
    ::: pointerScanNS 1 10 20 \
    ::: allocPeriodNS 10 100 1000 > all.dat
#    ::: w_true 0.00625 0.0125 0.25 \

cat 1>&2 <<EOF
Run
$ gnuplot -persist all.gnuplot
to plot the results.
EOF
