#!/bin/sh

# Simulate a range of w_true, pointerScanNS, and allocPeriodNS. The
# result can be plotted with all.gnuplot.

set -e

configs=()
for w_true in 0.00625 0.0125 0.25; do
    for pointerScanNS in 1 10 20; do
        for allocPeriodNS in 10 100 1000; do
            configs+=("--w_true $w_true --pointerScanNS $pointerScanNS --allocPeriodNS $allocPeriodNS")
        done
    done
done

out=all.dat
rm -f $out
n=1
for config in "${configs[@]}"; do
    echo -ne "\rConfiguration $n/${#configs[@]}..."
    ./simulate $config >> $out
    echo >> $out
    echo >> $out
    n=`expr $n + 1`
done
echo

cat 1>&2 <<EOF
Run
$ gnuplot -persist all.gnuplot
to plot the results.
EOF
